// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEg2O9J9boSTrq2_tXKqI7bdUFaKoctU0',
    appId: '1:748171418327:web:f4cb663606739c0befae92',
    messagingSenderId: '748171418327',
    projectId: 'hivemind-1',
    authDomain: 'hivemind-1.firebaseapp.com',
    storageBucket: 'hivemind-1.appspot.com',
    measurementId: 'G-L5TEXBJ89E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3Z3468NPqOwGy7FC8ehyaXlce2KVvJw',
    appId: '1:748171418327:android:fc96703f36542302efae92',
    messagingSenderId: '748171418327',
    projectId: 'hivemind-1',
    storageBucket: 'hivemind-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDshGP2Wx0-rQjpFR1XzW3ZPArJKdiGQ_M',
    appId: '1:748171418327:ios:7aff2466eef95d51efae92',
    messagingSenderId: '748171418327',
    projectId: 'hivemind-1',
    storageBucket: 'hivemind-1.appspot.com',
    iosClientId: '748171418327-k1lbd780jfm6itukensno7704i97195n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiveMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDshGP2Wx0-rQjpFR1XzW3ZPArJKdiGQ_M',
    appId: '1:748171418327:ios:7aff2466eef95d51efae92',
    messagingSenderId: '748171418327',
    projectId: 'hivemind-1',
    storageBucket: 'hivemind-1.appspot.com',
    iosClientId: '748171418327-k1lbd780jfm6itukensno7704i97195n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiveMind',
  );
}
